#!/bin/bash

ipython profile create
echo "c.InteractiveShellApp.extensions.append('sparkmonitor.kernelextension')" >>  $(ipython profile locate default)/ipython_kernel_config.py

git clone https://github.com/BigDataWUR/BigDataMOOC_content.git
mv ~/BigDataMOOC_content/datasets ~/BigDataMOOC_content/notebooks .
rm -rf BigDataMOOC_content

jupyter trust ~/notebooks/*.ipynb
jupyter trust ~/notebooks/module 2/*.ipynb
jupyter trust ~/notebooks/module 4/*.ipynb
jupyter trust ~/notebooks/module 5/*.ipynb

jupyter nbconvert --to notebook --execute --inplace ~/notebooks/setup.ipynb

rm ~/notebooks/setup.ipynb ~/notebooks/dummy.ipynb 

cat >> ~/.profile << EOF
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH
EOF


exec "$@"
