#!/bin/bash

ipython profile create
echo "c.InteractiveShellApp.extensions.append('sparkmonitor.kernelextension')" >>  $(ipython profile locate default)/ipython_kernel_config.py

git clone https://github.com/BigDataWUR/BigDataMOOC_content.git
mv /home/jovyan/BigDataMOOC_content/datasets /home/jovyan/BigDataMOOC_content/notebooks /home/jovyan/
rm -rf BigDataMOOC_content

#setup and spark test notebooks
jupyter trust /home/jovyan/notebooks/*.ipynb

#module 2 notebooks
jupyter trust /home/jovyan/notebooks/module 2/*.ipynb
jupyter trust /home/jovyan/notebooks/module 4/*.ipynb

jupyter nbconvert --to notebook --execute --inplace /home/jovyan/notebooks/setup.ipynb

cat >> ~/.profile << EOF
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH
EOF


exec "$@"
