name: Cache build to mybinder.org
on: [push]
jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@0.2
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
        IMAGE_NAME: BigDataWUR/BigDataMOOC